      SUBROUTINE STEPSCAN
      INCLUDE 'SIZES'
      COMMON /SCANR / ISCAN,NSCAN,STEPS,STARTS,LIMS,NDIM,IVALS
      INTEGER ISCAN,NSCAN,IVALS(3*NUMATM),NDIM
      DOUBLE PRECISION STEPS(3*NUMATM),STARTS(3*NUMATM),LIMS(3*NUMATM)
      COMMON /ALTCON / TRLB, ROTB, ROTD, ATMS, ICONXN, APPLIED,
     1                  VALS, NVALS
      INTEGER TRLB, ROTB, ROTD, ATMS, ICONXN(6,NUMATM),NVALS,MAXLIM
      LOGICAL APPLIED
      DOUBLE PRECISION VALS(3*NUMATM),ATOT(3,3)
      IF(NDIM.GT.0)THEN
      VALS(IVALS(1))=VALS(IVALS(1))+STEPS(1)
      IF(VALS(IVALS(1)).EQ.STARTS(1).OR.VALS(IVALS(1)).EQ.LIMS(1))THEN
      DO I=1,NDIM
      IF(VALS(IVALS(I)).EQ.STARTS(I).OR.VALS(IVALS(I)).EQ.LIMS(I))THEN
          MAXLIM=I
      ENDIF
      END DO
      DO I=MAXLIM,1,-1
        STEPS(I)=-STEPS(I)
      END DO
      MAXLIM=MAXLIM+1
      VALS(MAXLIM)=VALS(MAXLIM)+STEPS(MAXLIM)
      ENDIF
      ENDIF
      ISCAN=ISCAN+1
      RETURN
      END


      SUBROUTINE ADDSCAN(START,STEP,NUM)
**************************************************************************
*
*       MUST BE CALLED IMMEDIATELY AFTER ADDTRLB/BANGLE/DIHDR
*
**************************************************************************
      INCLUDE 'SIZES'
      COMMON /SCANR / ISCAN,NSCAN,STEPS,STARTS,LIMS,NDIM,IVALS
      INTEGER ISCAN,NSCAN,IVALS(3*NUMATM),NDIM
      DOUBLE PRECISION STEPS(3*NUMATM),STARTS(3*NUMATM),LIMS(3*NUMATM)
      COMMON /ALTCON / TRLB, ROTB, ROTD, ATMS, ICONXN, APPLIED,
     1                  VALS, NVALS
      INTEGER TRLB, ROTB, ROTD, ATMS, ICONXN(6,NUMATM),NVALS,MAXLIM
      LOGICAL APPLIED
      DOUBLE PRECISION VALS(3*NUMATM),ATOT(3,3),START,STEP
      NDIM=NDIM+1
      IVALS(NDIM)=NVALS
      STARTS(NDIM)=START
      LIMS(NDIM)=START+(NUM)*STEP
      NSCAN=NSCAN*(NUM+1)
      END

