      SUBROUTINE WRTXYZ(ICAL)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INCLUDE 'SIZES'
      COMMON /NUMCAL/ NUMCAL
      COMMON /GENRAL/ COORD(3,NUMATM), COLD(3,NUMATM*3), GOLD(MAXPAR),
     1 XPARAM(MAXPAR)
      COMMON /MOLKST/ NUMAT,NAT(NUMATM),NFIRST(NUMATM),NMIDLE(NUMATM),
     1                NLAST(NUMATM), NORBS, NELECS,NALPHA,NBETA,
     2                NCLOSE,NOPEN,NDUMY,FRACT
      COMMON /AXES / XHAT,YHAT,ZHAT,OFF,ATOT
      COMMON /PERMUTE / PR,PRT
      COMMON /SCANR / ISCAN,NSCAN,STEPS,STARTS,LIMS,NDIM,IVALS,REDSCN
      INTEGER ISCAN,NSCAN,IVALS(3*NUMATM),NDIM
      DOUBLE PRECISION STEPS(3*NUMATM),STARTS(3*NUMATM),LIMS(3*NUMATM)
      DOUBLE PRECISION XHAT(3),YHAT(3),ZHAT(3),OFF(3),ATOT(3,3)
      COMMON /ELEMTS/ ELEMNT(107)
      INTEGER PR(NUMATM),PRT(NUMATM)
      LOGICAL START,REDSCN
      SAVE START
      CHARACTER :: GETNAM*80
      CHARACTER*2 ELEMNT
      DATA START /.TRUE./
      IF(START)THEN
      IF(.NOT.REDSCN)THEN
      OPEN(UNIT=24,FILE=GETNAM('FOR024'),STATUS='REPLACE')
      ELSE
      OPEN(UNIT=24,FILE=GETNAM('FOR024'),ACCESS='APPEND')
      ENDIF
      START=.FALSE.
      ENDIF
      WRITE(24,'(I4)')INT(NUMAT)
      WRITE(24,'(A,1X,I6)')'CALCULATION #',ICAL
      WRITE(24,'(A2,4X,F16.10,F16.10,F16.10)')
C     1  (I,ELEMNT(NAT(I)),(COORD(J,I),J=1,3),I=1,NUMAT)
     1  (ELEMNT(NAT(PRT(I))),ATOT(1,1)*COORD(1,PRT(I))+
     2 ATOT(1,2)*COORD(2,PRT(I))+ ATOT(1,3)*COORD(3,PRT(I))+
     3 OFF(1),ATOT(2,1)*COORD(1,PRT(I))+ATOT(2,2)*COORD(2,PRT(I))+
     4 ATOT(2,3)*COORD(3,PRT(I))+OFF(2), ATOT(3,1)*COORD(1,PRT(I))+
     5 ATOT(3,2)*COORD(2,PRT(I))+ATOT(3,3)*COORD(3,PRT(I))+OFF(3),
     6 I=1,NUMAT)
      END
      SUBROUTINE WRTENERGY(E)
      IMPLICIT DOUBLE PRECISION (A-H,O-Z)
      INCLUDE 'SIZES'
      COMMON /NUMCAL/ NUMCAL
      COMMON /GENRAL/ COORD(3,NUMATM), COLD(3,NUMATM*3), GOLD(MAXPAR),
     1 XPARAM(MAXPAR)
      COMMON /MOLKST/ NUMAT,NAT(NUMATM),NFIRST(NUMATM),NMIDLE(NUMATM),
     1                NLAST(NUMATM), NORBS, NELECS,NALPHA,NBETA,
     2                NCLOSE,NOPEN,NDUMY,FRACT
      COMMON /AXES / XHAT,YHAT,ZHAT,OFF,ATOT
      COMMON /PERMUTE / PR,PRT
      COMMON /SCANR / ISCAN,NSCAN,STEPS,STARTS,LIMS,NDIM,IVALS,REDSCN
      COMMON /ALTCON / TRANSL, BANGL, DIHDR, ATOMS, ICONXN, APPLIED,
     1                  VALS, NVALS,NTRANS,NANGL,NDIHD,NATOM
      INTEGER TRANSL(5*NUMATM),NTRANS,BANGL(6*NUMATM),NANGL,
     1         DIHDR(7*NUMATM),NDIHD,ATOMS(NUMATM*NUMATM),
     2         NATOM,ICONXN(6,NUMATM),NVALS
      LOGICAL APPLIED
      DOUBLE PRECISION VALS(3*NUMATM)
      INTEGER ISCAN,NSCAN,IVALS(3*NUMATM),NDIM
      DOUBLE PRECISION STEPS(3*NUMATM),STARTS(3*NUMATM),LIMS(3*NUMATM)
      DOUBLE PRECISION XHAT(3),YHAT(3),ZHAT(3),OFF(3),ATOT(3,3),E
      COMMON /ELEMTS/ ELEMNT(107)
      INTEGER PR(NUMATM),PRT(NUMATM)
      LOGICAL START,REDSCN
      SAVE START
      CHARACTER :: GETNAM*80
      CHARACTER FORMAT*16
      DATA START /.TRUE./
      IF(NSCAN.LT.1.OR.NDIM.EQ.0)RETURN
      IF(START)THEN
      IF(.NOT.REDSCN)THEN
      OPEN(UNIT=28,FILE=GETNAM('FOR028'),STATUS='REPLACE')
      ELSE
      OPEN(UNIT=28,FILE=GETNAM('FOR028'),ACCESS='APPEND')
      ENDIF
      START=.FALSE.
      ENDIF
      WRITE(FORMAT,'(I16)')NDIM
      FORMAT=FORMAT(INDEX(FORMAT,' ',.TRUE.):)
      WRITE(28,'('//FORMAT//'ES20.12,ES20.12)')(VALS(IVALS(I)),
     1                                         I=1,NDIM),E
      END
